export const COMPETITION_LOADING = 'COMPETITION_LOADING';
export const COMPETITION_LOAD_ERROR = 'COMPETITION_LOAD_ERROR'
export const COMPETITION_LOAD_SUCCESS = 'COMPETITION_LOAD_SUCCESS'
export const COMPETITIONS_LOAD_SUCCESS = 'COMPETITIONS_LOAD_SUCCESS'
export const FEATURED_LOAD_SUCCESS = 'FEATURED_LOAD_SUCCESS'
export const FEATURED_LOAD_ERROR = 'FEATURED_LOAD_ERROR'


