# Generated by Django 3.0.7 on 2020-07-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0006_remove_order_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descrption',
            new_name='description',
        ),
    ]
