# Generated by Django 3.0.7 on 2020-07-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0008_auto_20200703_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='belong_to',
        ),
        migrations.AddField(
            model_name='competition',
            name='groups',
            field=models.ManyToManyField(related_name='competitions', to='paradise.Competition_Group'),
        ),
    ]
