# Generated by Django 3.0.7 on 2020-07-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0009_auto_20200703_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
