# Generated by Django 3.0.7 on 2020-07-04 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0010_ecard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='prize_to_win',
        ),
        migrations.AddField(
            model_name='competition',
            name='prize_to_win',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='paradise.Prize'),
        ),
    ]
