# Generated by Django 3.0.7 on 2020-07-05 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paradise', '0011_auto_20200704_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_ticket', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='competition',
            name='no_of_winners',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ManyToManyField(to='paradise.Coupon'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paradise.Competition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_ticket',
            field=models.CharField(default='A1234', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='prize_to_win',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paradise.Prize'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paradise.Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='winner',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paradise.Competition'),
        ),
        migrations.AddField(
            model_name='winner',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
