# Generated by Django 3.0.7 on 2020-07-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0012_auto_20200705_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='groups',
            field=models.ManyToManyField(null=True, related_name='competitions', to='paradise.Competition_Group'),
        ),
        migrations.AlterField(
            model_name='ecard',
            name='image',
            field=models.ImageField(upload_to='ecards'),
        ),
    ]
