# Generated by Django 3.0.7 on 2020-07-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0013_auto_20200705_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowToPLay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='ticket_end',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='competition',
            name='ticket_numbers',
            field=models.CharField(choices=[('100', '00 - 99'), ('200', '000 - 199'), ('300', '000 - 299'), ('400', '000 - 399'), ('500', '000 - 499'), ('600', '000 - 599')], default='100', max_length=3),
        ),
        migrations.AddField(
            model_name='competition',
            name='ticket_start',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], default='A', max_length=1),
        ),
    ]
