# Generated by Django 3.0.7 on 2020-07-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0014_auto_20200716_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='ticket_end',
            new_name='ticket_letter_end',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='ticket_start',
            new_name='ticket_letter_start',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='ticket_numbers',
        ),
        migrations.AddField(
            model_name='competition',
            name='ticket_number_end',
            field=models.CharField(choices=[('100', '99'), ('200', '199'), ('300', '299'), ('400', '399'), ('500', '499'), ('600', '599')], default='100', max_length=3),
        ),
        migrations.AddField(
            model_name='competition',
            name='ticket_number_start',
            field=models.CharField(choices=[('100', '00'), ('100+', '000')], default='100', max_length=4),
        ),
        migrations.AlterField(
            model_name='competition',
            name='groups',
            field=models.ManyToManyField(related_name='competitions', to='paradise.Competition_Group'),
        ),
    ]
