# Generated by Django 3.0.7 on 2020-07-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0016_auto_20200722_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='price',
            field=models.IntegerField(),
        ),
    ]
