# Generated by Django 3.0.7 on 2020-07-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0017_auto_20200726_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
