# Generated by Django 3.0.7 on 2020-07-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0022_auto_20200726_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LiveDraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
