# Generated by Django 3.0.7 on 2020-07-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0023_howitworks_livedraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedraw',
            name='appID',
            field=models.CharField(default=345, max_length=100),
            preserve_default=False,
        ),
    ]
