# Generated by Django 3.0.7 on 2020-07-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0024_livedraw_appid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prize',
            name='image',
        ),
        migrations.AddField(
            model_name='prize',
            name='media_1',
            field=models.FileField(blank=True, null=True, upload_to='prizes/'),
        ),
        migrations.AddField(
            model_name='prize',
            name='media_1_type',
            field=models.CharField(default='video', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prize',
            name='media_2',
            field=models.FileField(blank=True, null=True, upload_to='prizes/'),
        ),
        migrations.AddField(
            model_name='prize',
            name='media_2_type',
            field=models.CharField(default='image', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prize',
            name='media_3',
            field=models.FileField(blank=True, null=True, upload_to='prizes/'),
        ),
        migrations.AddField(
            model_name='prize',
            name='media_3_type',
            field=models.CharField(default='image', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prize',
            name='media_4',
            field=models.FileField(blank=True, null=True, upload_to='prizes/'),
        ),
        migrations.AddField(
            model_name='prize',
            name='media_4_type',
            field=models.CharField(default='image', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prize',
            name='media_5',
            field=models.FileField(blank=True, null=True, upload_to='prizes/'),
        ),
        migrations.AddField(
            model_name='prize',
            name='media_5_type',
            field=models.CharField(default='image', max_length=5),
            preserve_default=False,
        ),
    ]
