# Generated by Django 3.0.7 on 2020-07-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0025_auto_20200730_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='live_draw_url',
            field=models.CharField(default='link', max_length=1000),
            preserve_default=False,
        ),
    ]
