# Generated by Django 3.0.7 on 2020-07-30 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0026_winner_live_draw_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
